In [1]:
import os
os.environ['KERAS_BACKEND'] = 'theano'
import keras

Using Theano backend.


In [7]:
from scipy import misc
import glob
import numpy as np
from sklearn.model_selection import train_test_split






def format_output(l):
    ret = []
    for i in range(len(l)):
        n = []
        for j in range(26):
            if j == l[i]:
                n.append(1)
            else:
                n.append(0)
        ret.append(np.array(n))
    return np.array(ret)


Data_images_list = []
Data_labels_list = []


for i in range(26):
    name = str(i)
    for image_path in glob.glob("C:/Users/SANDHU/Desktop/AI/Train_data/Train_data/" + name + "/*.jpg"):
        image = misc.imread(image_path)
        Data_images_list.append(list(image))
        Data_labels_list.append(i)

print(len(Data_labels_list))

Data_images = np.array(Data_images_list)
Data_labels = format_output(Data_labels_list)

print(Data_labels.shape)
#CNN_data_list = []
#CNN_labels_list = []


#print(len(Data_images))
#print(len(Data_labels))

#for i in range(len(Data_images)):
 #   CNN_data_list.append(normalise(Data_images[i]))
  #  CNN_labels_list.append(Data_labels[i])

#CNN_data = np.array(CNN_data_list)
#CNN_labels = np.array(CNN_labels_list)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:31: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.


25000
(25000, 26)


In [3]:
#CNN_labels.shape

In [4]:
#CNN_data.shape

In [8]:
x_train, x_test, y_train, y_test = train_test_split(Data_images, Data_labels, test_size = 0.2, shuffle = True)

In [9]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(20000, 128, 128)
(5000, 128, 128)
(20000, 26)
(5000, 26)


In [10]:
from keras.models import Sequential,Input,Model
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.layers.advanced_activations import LeakyReLU

In [11]:
cnn = Sequential()

In [12]:


cnn.add(Conv2D(40, kernel_size=(15, 15), strides=(1, 1),
                 activation='relu',
                 input_shape=(128,128,1)))
cnn.add(LeakyReLU(alpha=0.1))
cnn.add(MaxPooling2D(2, 2))

cnn.add(Conv2D(80, kernel_size=(12, 12), strides=(1, 1),
                 activation='relu'))
#cnn.add(LeakyReLU(alpha=0.1))
cnn.add(MaxPooling2D(2, 2))


cnn.add(Conv2D(160, kernel_size=(8, 8), strides=(1, 1),
                 activation='relu'))
#cnn.add(LeakyReLU(alpha=0.1))
cnn.add(MaxPooling2D(2, 2))


cnn.add(Conv2D(80, kernel_size=(3, 3), strides=(1, 1),
                 activation='relu'))
#cnn.add(LeakyReLU(alpha=0.1))
cnn.add(MaxPooling2D(2, 2))
        
    

cnn.add(Flatten())

cnn.add(Dense(1000, activation='relu'))
cnn.add(Dense(100, activation='relu'))

cnn.add(Dense(26, activation='softmax'))

In [13]:

cnn.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.SGD(lr=0.01),
              metrics=['accuracy'])


In [14]:
cnn.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 114, 114, 40)      9040      
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 114, 114, 40)      0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 57, 57, 40)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 46, 46, 80)        460880    
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 23, 23, 80)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 16, 16, 160)       819360    
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 8, 8, 160)         0         
__________

In [12]:
#print((x_train.T).shape)

In [13]:
#print(x_train.T[:,:,0:1])

In [14]:
#print(x_train[0])

In [15]:
#x = x_train.reshape((18652,128,128,1))

In [16]:
#print(x[0])

In [15]:
x_data, x_valid , y_data, y_valid = train_test_split(x_train,y_train, test_size = 0.2)
x_data = x_data.astype(float)

x_valid = x_valid.astype(float)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
for i in range(len(x_data)):
    scaler.fit(x_data[i])
    x_data[i] = scaler.transform(x_data[i])

for i in range(len(x_valid)):
    scaler.fit(x_valid[i])
    x_valid[i] = scaler.transform(x_valid[i])

print(x_data[0])


print(x_data.shape)
print(x_valid.shape)
print(y_data.shape)
print(y_valid.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(16000, 128, 128)
(4000, 128, 128)
(16000, 26)
(4000, 26)


In [16]:
np.unique(x_data[0])

array([0.        , 0.00392157, 0.00784314, 0.01176471, 0.01568627,
       0.01960784, 0.02352941, 0.02745098, 0.03137255, 0.03529412,
       0.03921569, 0.04313725, 0.04705882, 0.05098039, 0.05490196,
       0.05882353, 0.0627451 , 0.06666667, 0.06666667, 0.07058824,
       0.0745098 , 0.07692308, 0.07843137, 0.08235294, 0.08627451,
       0.09019608, 0.09411765, 0.09803922, 0.10196078, 0.10588235,
       0.11111111, 0.11764706, 0.1254902 , 0.12941176, 0.13333333,
       0.1372549 , 0.15789474, 0.16666667, 0.26666667, 0.33333333,
       0.36842105, 0.38888889, 0.44444444, 0.46153846, 0.46666667,
       0.5       , 0.53333333, 0.53846154, 0.55555556, 0.61111111,
       0.61538462, 0.63157895, 0.66666667, 0.68421053, 0.69230769,
       0.72222222, 0.73684211, 0.76923077, 0.77777778, 0.78947368,
       0.8       , 0.83333333, 0.84210526, 0.84615385, 0.85490196,
       0.86666667, 0.87843137, 0.88235294, 0.88627451, 0.88888889,
       0.89019608, 0.89411765, 0.89473684, 0.90196078, 0.90588

In [18]:



x = x_data.reshape(16000, 128, 128, 1)
x_v = x_valid.reshape(4000, 128, 128, 1)

In [19]:
trained_cnn = cnn.fit(x, y_data, batch_size = 64,   epochs = 4,  verbose=1,  validation_data=(x_v, y_valid))

Train on 16000 samples, validate on 4000 samples
Epoch 1/4
16000/16000 [==============================] - 3254s 203ms/step - loss: 1.7120 - acc: 0.5064 - val_loss: 0.1003 - val_acc: 0.9705
Epoch 2/4
16000/16000 [==============================] - 3044s 190ms/step - loss: 0.0745 - acc: 0.9771 - val_loss: 0.0276 - val_acc: 0.9930
Epoch 3/4
16000/16000 [==============================] - 3014s 188ms/step - loss: 0.0464 - acc: 0.9899 - val_loss: 2.6759 - val_acc: 0.5055
Epoch 4/4
16000/16000 [==============================] - 3011s 188ms/step - loss: 0.0596 - acc: 0.9867 - val_loss: 0.0134 - val_acc: 0.9965


In [ ]:
#print(np.unique(Data_labels))

In [33]:
from sklearn.externals import joblib

joblib.dump(cnn,'CNN_Model.joblib')
joblib.dump(cnn,'CNN_Model.sav')

['CNN_Model.sav']

In [21]:
saved_model=joblib.load('CNN_Model.joblib')

In [44]:
print(np.argmax(cnn.predict(x_test[0].reshape(1,128,128,1))))
print(np.argmax(y_test[0]))

22
22
